name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        working-directory: nba_probs
        run: pip install -e .[dev]

      - name: Ruff
        working-directory: nba_probs
        run: ruff check .

      - name: Mypy
        working-directory: nba_probs
        run: mypy src

      - name: Pytest
        working-directory: nba_probs
        run: pytest
